# Generated by Django 5.2.3 on 2025-06-13 03:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('influence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20)),
                ('interest', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('investor', 'Investor'), ('regulator', 'Regulator'), ('community', 'Community'), ('media', 'Media')], default='internal', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_generated_insights', models.TextField(blank=True, help_text='AI-generated insights about this stakeholder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('meeting', 'Meeting'), ('email', 'Email'), ('phone', 'Phone Call'), ('presentation', 'Presentation'), ('workshop', 'Workshop'), ('survey', 'Survey'), ('interview', 'Interview'), ('other', 'Other')], default='meeting', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='planned', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('effectiveness_rating', models.IntegerField(blank=True, help_text='Rate effectiveness from 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of the engagement')),
                ('ai_action_items', models.TextField(blank=True, help_text='AI-extracted action items')),
                ('ai_sentiment_analysis', models.TextField(blank=True, help_text='AI sentiment analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to=settings.AUTH_USER_MODEL)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('reports_to', 'Reports To'), ('manages', 'Manages'), ('collaborates', 'Collaborates With'), ('influences', 'Influences'), ('depends_on', 'Depends On'), ('conflicts', 'Has Conflict With'), ('supports', 'Supports')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('strength', models.CharField(choices=[('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='stakeholders.stakeholder')),
                ('to_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='stakeholders.stakeholder')),
            ],
            options={
                'unique_together': {('from_stakeholder', 'to_stakeholder', 'relationship_type')},
            },
        ),
    ]
