# Generated by Django 5.2.3 on 2025-06-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagement',
            options={'ordering': ['scheduled_date']},
        ),
    ]
