# Generated by Django 5.2.3 on 2025-07-03 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_alter_engagement_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo_mode', models.BooleanField(default=False)),
                ('demo_started_at', models.DateTimeField(auto_now_add=True)),
                ('demo_scenario', models.CharField(choices=[('standard', 'Standard Demo'), ('tech_startup', 'Tech Startup'), ('enterprise_project', 'Enterprise Project'), ('product_launch', 'Product Launch')], default='standard', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
